### ISSUE TITLE
Plugin does not work w/ java-library plugin

### ISSUE THREAD

**Issue by sdavids** [andreas-schilling/joda-beans-gradle-plugin#2]
https://docs.gradle.org/current/userguide/java_library_plugin.html

> The compile [...] configurations inherited from the Java plugin are still available but are deprecated. You should avoid using them, as they are only kept for backwards compatibility.

```
api("org.joda:joda-beans:1.13")
```

will lead to:

```
./gradlew jodaGenerate
...
> Task :jodaGenerate
Skipping as Joda-Beans is not in the project compile classpath
```

Workaround:

```
compile("org.joda:joda-beans:1.13")
```

**Comment by andreas-schilling** [comment]
Fixed with version 1.0.4. Available from bintray, after sync soon also from Maven central.
Of course, kudos for finding the bug!
